[package]
name = "texture_galaxy"
version = "0.1.0"
authors = ["Nelson Kossuga <nelsonkossuga@gmail.com>"]
edition = "2021"

[dependencies]
nannou = "0.18.1"
rand = "0.8.5"
typed-builder = "0.11.0"

[[bin]]
name = "texture_galaxy"
path = "src/main.rs"